"""Add image_url to Event model

Revision ID: 392b61bdf1ad
Revises: 4476c1018c56
Create Date: 2025-01-14 01:09:50.359389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392b61bdf1ad'
down_revision = '4476c1018c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
