"""Update SavedEvent model to reference Event table

Revision ID: 4476c1018c56
Revises: d68ab37e5eb4
Create Date: 2025-01-11 19:51:18.706710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4476c1018c56'
down_revision = 'd68ab37e5eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_event', schema=None) as batch_op:
        batch_op.drop_column('event_name')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_image_url')
        batch_op.drop_column('event_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
