"""Add profile_picture to User model

Revision ID: 792f67f74e89
Revises: ca163dcfcd7d
Create Date: 2024-12-21 21:50:46.746294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792f67f74e89'
down_revision = 'ca163dcfcd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.Text(), nullable=True))
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
