"""Add api_event_id to Event model

Revision ID: 80264bf1f59e
Revises: 792f67f74e89
Create Date: 2025-01-09 01:15:58.119719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80264bf1f59e'
down_revision = '792f67f74e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_event_id', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['api_event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_event_id')

    # ### end Alembic commands ###
