"""Update models for user friendships and profile pictures

Revision ID: ca163dcfcd7d
Revises: e083dbac9197
Create Date: 2024-12-21 21:02:08.379515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca163dcfcd7d'
down_revision = 'e083dbac9197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=200), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
