"""adding event_name, event_image_url, event_date, event_location into SavedEvent Model

Revision ID: d68ab37e5eb4
Revises: 06fa1163caf8
Create Date: 2025-01-11 19:17:10.354861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68ab37e5eb4'
down_revision = '06fa1163caf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('event_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('event_location', sa.String(length=200), nullable=True))
        batch_op.drop_column('api_event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_event_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('event_location')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_image_url')
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
